version: 2.1
executors:
  default:
    docker:
      - image: circleci/golang:1.12-node

jobs:
  lint:
    executor:
      name: default
    steps:
      - checkout
      - run: make check-style

  test:
    executor:
      name: default
    steps:
      - checkout
      - run: make test

  cover:
    executor:
      name: default
    steps:
      - checkout
      - run: sh ./test.sh
      - run: bash <(curl -s https://codecov.io/bash)
  
workflows:
  version: 2
  untagged-build:
    jobs:
      - lint
      - test
      - cover
