// This file is automatically generated. Do not modify it manually.

package config

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var Manifest *model.Manifest

const manifestStr = `
{
  "id": "com.mattermost.plugin-suggestions",
  "name": "Suggestions",
  "description": "This plugin give users some suggestions.",
  "version": "0.1.0",
  "min_server_version": "5.24.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": []
  }
}
`

func init() {
	Manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
